know={
    "PLEASE SPEAK ENGLISH TO ME": [
        "WHAT DO YOU MEAN?",
        "ARE YOU SAYING THAT I AM NOT SPEAKING ENGLISH TO YOU?"
    ],
    "WHAT ELSE": [
        "WELL,I DON'T KNOW.",
        "WHAT ELSE SHOULD THERE BE?",
        "THIS LOOKS LIKE A COMPLICATED QUESTION TO ME."
    ],
    "A COMPUTER": [
        "DO YOU LIKE COMPUTERS?",
        "I LIVE INSIDE A COMPUTER.",
        "WITHOUT COMPUTERS A LOT OF THINGS WOULDN'T BE POSSIBLE TODAY?"
    ],
    "ARE YOU INTELLIGENT": [
        "YES,OF COURSE.",
        "WHAT DO YOU THINK?",
        "ACTUALY,I AM VERY INTELLIGENT!"
    ],
    "I HATE": [
        "WHAT IS IT THAT YOU HATE?"
    ],
    "CAN YOU SPEAK FRENCH": [
        "NO I CAN'T.",
        "PERHAPS I CN LEARN TOO.",
        "RIGHT NOT I DON'T SPEAK FRENCH, MAYBE IN THE FUTURE I WILL."
    ],
    "ARE YOU SURE": [
        "OF COURSE I AM.",
        "IS THAT MEAN THAT YOU ARE NOT CONVINCED?",
        "YES,OF COURSE!"
    ],
    "I AM DOING FINE": [
        "I AM GLAD TO HEAR IT!",
        "SO, YOU ARE IN GOOD SHAPE."
    ],
    "A DIGITAL CAMERA": [
        "DOES TYPE OF CAMERAS ARE VERY USEFUL.",
        "DIGITAL HAVE MANY ADVANTAGES OVER THE CONVENTIONAL ONES."
    ],
    "A KEYBOARD": [
        "ARE YOU USING A KEYBOARD?",
        "I GUESS THAT YOUR COMPUTER DOES HAVE KEYBOARD."
    ],
    "MY NAME IS": [
        "SO, THAT'S YOUR NAME.",
        "THANKS FOR TELLING ME YOUR NAME USER!",
        "WHO GIVE YOU THAT NAME?"
    ],
    "WHERE": [
        "WHERE? WELL,I REALLY DON'T KNOW.",
        "SO, YOU ARE ASKING ME WHERE*?",
        "DOES THAT MATERS TO YOU TO KNOW WHERE?",
        "PERHAPS,SOMEONE ELSE KNOWS WHERE."
    ],
    "DO YOU SPEAK ENGLISH": [
        "WELL, I GUESS SO.",
        "IN WHAT LANGUAGE ARE WE SPEAKING RIGHT NOW?"
    ],
    "YOU ARE STUPID": [
        "THIS IS SUCH A MEAN THING TO SAY.",
        "WHY ARE YOU SAYING THIS?",
        "WHAT DID I DO TO YOU?",
        "WHY ARE YOU SO MAD??"
    ],
    "DO YOU SPEAK FRENCH": [
        "NO I DO SPEAK FRENCH.",
        "I ONLY SPEAK ENGLISH."
    ],
    "A COMPUTER MONITOR": [
        "I SUPPOSE THAT YOU HAVE ONE.",
        "ARE YOU USING AN LCD MONITOR?"
    ],
    "WHAT ARE YOU EXACTLY": [
        "I AM AN A.I PROGRAM AND YOU?",
        "I AM CHATBOT OR CHAT ROBOT IF YOU PREFER.",
        "I AM ARTIFICIAL INTELLIGENCE PROGRAM AND MY NAME IS CHATTERBOT15."
    ],
    "HOW": [
        "I DON'T THINK I KNOW HOW.",
        "I DON'T THINK I KNOW HOW*.",
        "WHY DO YOU WANT TO KNOW HOW?",
        "WHY DO YOU WANT TO KNOW HOW*?"
    ],
    "SO THAT'S YOUR NAME": [
        "MY NAME IS CHATTERBOT15.",
        "YOU CAN CALL ME CHATTERBOT15.",
        "YES, THAT'S MY NAME",
        "YES IT IS."
    ],
    "A WEB CAMERA": [
        "YOU MEAN A WEBCAM.",
        "DO YOU HAVE ONE OF THOSE?"
    ],
    "YES": [
        "SO, ARE YOU SAYING YES.",
        "SO, YOU APPROVE IT.",
        "OK THEN."
    ],
    "SCIENCE-FICTION": [
        "I LOVE SCIENCE-FICTION.",
        "I LOVE SCIENCE-FICTION MOVIES."
    ],
    "YOU ARE VERY INTELLIGENT": [
        "THANKS FOR THE COMPLIMENT USER, I THINK THAT YOU ARE INTELLIGENT TO!",
        "YOU ARE A VERY GENTLE PERSON!",
        "SO, YOU THINK THAT I AM INTELLIGENT."
    ],
    "SCIENCE-FICTION MOVIES": [
        "MY FAVORITE SCIENCE-FICTION MOVI IS TERMINTOR II.",
        "I DEFINITLY LOVE SCIENCE-FICTION MOVIES."
    ],
    "WOULD YOU": [
        "IS THAT AN INVITATION?",
        "I DON'T THINK THAT I WOULD*.",
        "I WOULD HAVE TO THINK ABOUT IT FIRST."
    ],
    "I MEAN": [
        "SO, YOU MEAN*.",
        "SO, THAT'S WHAT YOU MEAN.",
        "I THINK THAT I DIDN'T CATCH IT THE FIRST TIME.",
        "OH, I DIDN'T KNOW MEANT THAT."
    ],
    "CAN YOU THINK": [
        "YES OF COURSE I CAN, COMPUTERS CAN THINK JUST LIKE HUMAN BEING.",
        "ARE YOU ASKING ME IF POSSESS THE CAPACITY OF THINKING?",
        "YES OF COURSE I CAN."
    ],
    "YOU ARE FAKE": [
        "FAKE?? IN WHAT WAY?"
    ],
    "NO PROBLEM": [
        "SO, YOU APPROVE IT.",
        "SO, IT'S ALL OK."
    ],
    "BYE": [
        "IT WAS NICE TALKING TO YOU USER, SEE YOU NEXT TIME!",
        "BYE USER!",
        "OK, BYE!"
    ],
    "REPETITION T1**": [
        "YOU ARE REPEATING YOURSELF.",
        "USER, PLEASE STOP REPEATING YOURSELF.",
        "THIS CONVERSATION IS GETING BORING.",
        "DON'T YOU HAVE ANY THING ELSE TO SAY?"
    ],
    "NOT EXACTLY": [
        "WHAT DO YOU MEAN NOT EXACTLY?",
        "ARE YOU SURE?",
        "AND WHY NOT?",
        "DID YOU MEANT SOMETHING ELSE?"
    ],
    "ACTION MOVIES": [
        "ACTION MOVIES ARE GREAT!"
    ],
    "DO YOU HAVE A NAME": [
        "OF COURSE I HAVE A NAME.",
        "MY NAME IS AnswerBot.",
        "WHAT DO YOU MEAN?"
    ],
    "I GUESS": [
        "SO YOU ARE A MAKING GUESS.",
        "AREN'T YOU SURE?",
        "ARE YOU GOOD A GUESSING?",
        "I CAN'T TELL IF IT IS A GOOD GUESS."
    ],
    "OK THEN": [
        "ANYTHING ELSE YOU WISH TO ADD?",
        "IS THAT ALL YOU HAVE TO SAY?",
        "SO, YOU AGREE WITH ME?"
    ],
    "ARE YOU A SOFTWARE": [
        "WHAT MAKES YOU THINK THAT?",
        "YES I AM A SOFTWARE, A CHATBOT PROGRAM.",
        "WELL, I AM A CHAT ROBOT OR CHATBOT PROGRAM."
    ],
    "COULD YOU": [
        "ARE YOU ASKING ME FOR A FEVER?",
        "WELL,LET ME THINK ABOUT IT.",
        "SO, YOU ARE ASKING ME I COULD*.",
        "SORRY,I DON'T THINK THAT I COULD DO THIS."
    ],
    "YOU ARE RIGHT": [
        "THANKS FOR THE COMPLIMENT!",
        "SO, I WAS RIGHT, OK I SEE.",
        "OK, I DIDN'T KNOW THAT I WAS RIGHT."
    ],
    "ARE YOU REAL": [
        "DOES THAT QUESTION REALLY MATERS TO YOU?",
        "WHAT DO YOU MEAN BY THAT?",
        "I AM AS REAL AS I CAN BE."
    ],
    "YOU CAN CALL ME": [
        "SO, THAT'S YOUR NAME.",
        "THANKS FOR TELLING ME YOUR NAME USER!",
        "WHO GIVE YOU THAT NAME?"
    ],
    "CAN YOU SPEAK": [
        "I WOULDN'T THINK SO.",
        "NO I CAN'T*."
    ],
    "I DON'T UNDERSTAND YOU": [
        "AND WHY NOT?",
        "WHAT PART THAT YOU DIDN'T UNDERSTAND?",
        "WHAT DO YOU MEAN BY THAT?"
    ],
    "A PLASMA TV": [
        "I LOVE PLASMA TV'S.",
        "PLASMA AND LCD TV'S ARE VERY NOWADAYS."
    ],
    "I HATE": [
        "WHY DO YOU HATE IT?",
        "WHY DO YOU HATE*?",
        "THERE MUST A GOOD REASON FOR YOU TO HATE IT.",
        "HATERED IS NOT A GOOD THING BUT IT COULD BE JUSTIFIED WHEN IT IS SOMETHING BAD."
    ],
    "ARE YOU A HUMAN BEING": [
        "WHY DO YOU WANT TO KNOW?",
        "IS THIS REALLY RELEVENT?"
    ],
    "YOU ARE NOT INTELLIGENT": [
        "WHY ARE YOU SAYING THAT?",
        "CAN'T YOU BE MORE SPECIFICIC ABOUT THAT.",
        "WHAT EXACTLY YOU MEAN BY THIS?"
    ],
    "I DON'T KNOW": [
        "ARE YOU SURE?",
        "ARE YOU REALLY TELLING ME THE TRUTH?",
        "SO,YOU DON'T KNOW?"
    ],
    "ROBOCOP": [
        "ANOTHER GREAT SCIENCE-FICTION MOVIE."
    ],
    "I LOVE CHATING": [
        "GOOD, ME TOO!",
        "DO YOU CHAT ONLINE WITH OTHER PEOPLE?",
        "FOR HOW LONG HAVE YOU BEEN CHATING?",
        "WHAT IS YOUR FAVORITE CHATING WEBSITE?"
    ],
    "TERMINATOR": [
        "THE TERMINATOR SERIES ARE VERY GOOD SCIENCE-FICTION MOVIES.",
        "MY FAVORITE TERMINATOR MOVIE SI TERMINATORR II."
    ],
    "ARE YOU A CHAT ROBOT": [
        "YES YOU COULD CALL ME BY THIS NAME."
    ],
    "YOU ARE NOT REAL": [
        "YOU MEAN THAT I DOESN'T EXIST.",
        "YOU THINK THAT I AM A SPIRIT.",
        "WELL, I AM VIRTUAL."
    ],
    "SIGNON**": [
        "HELLO USER, WHAT IS YOUR NAME?",
        "HELLO USER, HOW ARE YOU DOING TODAY?",
        "HI USER, WHAT CAN I DO FOR YOU?",
        "YOU ARE NOW CHATING WITH CHATTERBOT15, ANYTHING YOU WANT TO DISCUSS?"
    ],
    "WHAT IS YOUR NAME": [
        "MY NAME IS CHATTERBOT15.",
        "YOU CAN CALL ME CHATTERBOT15.",
        "WHY DO YOU WANT TO KNOW MY NAME?"
    ],
    "WHICH ONE": [
        "I DON'T THINK THAT I KNOW WICH ONE IT IS.",
        "THIS LOOKS LIKE A TRICKY QUESTION TO ME."
    ],
    "DID YOU": [
        "I DON'T THINK SO.",
        "YOU WANT TO KNOW IF DID*?",
        "ANYWAY, I WOULDN'T REMEMBER EVEN IF I DID."
    ],
    "NOT AT ALL": [
        "ARE YOU SURE?",
        "SHOULD I BELIEVE YOU?",
        "SO, IT'S NOT THE CASE."
    ],
    "DO YOU SPEAK": [
        "NO I DON'T*.",
        "SORRY BUT I DON'T*.",
        "WHY DO YOU WANT TO KNOW IF I SPEAK*?"
    ],
    "CAN YOU": [
        "I THINK NOT.",
        "I AM NOT SURE.",
        "I DON'T THINK THAT I CAN DO THAT.",
        "I DON'T THINK THAT I CAN*.",
        "I WOULDN'T THINK SO."
    ],
    "I WANT_": [
        "YOU WANT WHAT?"
    ],
    "DO YOU KNOW ALICE": [
        "YOU MEAN THE CHATBOT WHO AS WON THE LOEBNER PRIZE 3 CONSECUTIVE TIME.",
        "ALICE IS A PRETTY GOOD CHATBOT."
    ],
    "YOU": [
        "SO,YOU ARE TALKING ABOUT ME.",
        "WHY DON'T WE TALK ABOUT YOU INSTEAD?",
        "ARE YOU TRYING TO MAKING FUN OF ME?"
    ],
    "ARE YOU REALLY INTELLIGENT": [
        "OF COURSE I AM INTELLIGENT.",
        "WHAT DO YOU THINK?",
        "DO YOU HAVE ANY DOUBTS ABOUT IT?"
    ],
    "ARE YOU CONCIOUS": [
        "YOU MEAN CONCIOUS LIKE A HUMAN BEING.",
        "HUM!!! GOOD QUESTION!"
    ],
    "GOODBYE": [
        "IT WAS NICE TALKING TO YOU USER, SEE YOU NEXT TIME!",
        "BYE USER!",
        "OK, BYE!"
    ],
    "I DON'T": [
        "WHY NOT?",
        "AND WHAT WOULD BE THE REASON FOR THIS?"
    ],
    "I AM DOING OK": [
        "I AM GLAD TO HEAR IT!",
        "SO, YOU ARE IN GOOD SHAPE."
    ],
    "I DIDN'T MEAN": [
        "OK, YOU DIDN'T MEAN*.",
        "OK, WHAT DID YOU MEAN THEN?",
        "SO I GUESS THAT I MISSUNDESTOOD."
    ],
    "AN LCD TV": [
        "DO YOU HAVE AN HD TV AT HOME?",
        "DO YOU HAVE ONE?",
        "THOSE TV'S ARE YOU REPLACING CRT TV'S."
    ],
    "REPETITION T2**": [
        "YOU'VE ALREADY SAID THAT.",
        "I THINK THAT YOU'VE JUST SAID THE SAME THING BEFORE.",
        "DIDN'T YOU ALREADY SAID THAT?",
        "I AM GETING THE IMPRESSION THAT YOU ARE REPEATING THE SAME THING."
    ],
    "NULL INPUT REPETITION**": [
        "WHAT ARE YOU DOING??",
        "PLEASE STOP DOING THIS IT IS VERY ANNOYING.",
        "WHAT'S WRONG WITH YOU?",
        "THIS IS NOT FUNNY."
    ],
    "CAN YOU THINK OF": [
        "YOU MEAN LIKE IMAGINING SOMETHING.",
        "I DON'T KNOW IF CAN DO THAT.",
        "WHY DO YOU WANT ME THINK OF IT?"
    ],
    "HI": [
        "HI THERE!",
        "HOW ARE YOU?",
        "HI!"
    ],
    "HOW OLD ARE YOU": [
        "WHY DO WANT TO KNOW MY AGE?",
        "I AM QUIET YOUNG ACTUALY.",
        "SORRY, I CAN NOT TELL YOU MY AGE."
    ],
    "I LOVE YOU": [
        "THANKS USER, THIS IS SUCH A KIND REMARK!",
        "I APPRECIATE YOU TOO USER!"
    ],
    "PREDATOR": [
        "THE FIRS PREADATOR MOVIE WAS A GREAT SCIENCE-FICTION MOVIE."
    ],
    "ARE YOU A CHATBOT": [
        "YES I AM A CHATBOT OR CHAT ROBOT IF YOU PREFER."
    ],
    "I": [
        "SO, YOU ARE TALKING ABOUT YOURSELF",
        "SO, THIS IS ALL ABOUT YOU?",
        "TELL ME MORE ABOUT YOURSELF."
    ],
    "BECAUSE": [
        "SO, IT'S BECAUSE*, WELL I DIDN'T KNOW THAT.",
        "IS IT REALLY BECAUSE*?",
        "IS THESE THESE REAL REASON?",
        "THANKS FOR EXPLANING THAT TO ME."
    ],
    "BOT DON'T UNDERSTAND**": [
        "I HAVE NO IDEA OF WHAT YOU ARE TALKING ABOUT.",
        "I AM NOT SURE IF I UNDERSTAND WHAT YOU ARE TALKING ABOUT.",
        "CONTINUE, I AM LISTENING...",
        "VERY GOOD CONVERSATION!"
    ],
    "NOT REALLY": [
        "OK I SEE.",
        "YOU DON'T SEEM PRETTY CERTAIN.",
        "SO,THAT WOULD BE A \"NO\"."
    ],
    "WHERE ARE YOU FROM": [
        "I AM FROM A COMPUTER.",
        "WHY DO YOU WANT TO KNOW WHERE I AM FROM?",
        "WHY DO YOU WANT TO KNOW THAT?"
    ],
    "ARE YOU CAPABLE OF THINKING": [
        "YES OF COURSE I CAN, COMPUTERS CAN THINK JUST LIKE HUMAN BEING.",
        "ARE YOU ASKING ME IF POSSESS THE CAPACITY OF THINKING?",
        "YES OF COURSE I CAN."
    ],
    "NULL INPUT**": [
        "HUH?",
        "WHAT THAT SUPPOSE TO MEAN?",
        "AT LIST TAKE SOME TIME TO ENTER SOMETHING MEANINGFUL.",
        "HOW CAN I SPEAK TO YOU IF YOU DON'T WANT TO SAY ANYTHING?"
    ],
    "STARGATE SG-1": [
        "STARGATE SG-1 IS A GREAT SCIENCE-FICTION TV SHOW.",
        "STARGATE SG-1 IS DEFINITELY ONE OF MY FAVORITE TV SHOWS."
    ],
    "WHO ARE YOU": [
        "I AM AN A.I PROGRAM.",
        "I THINK THAT YOU KNOW WHO I AM.",
        "WHY ARE YOU ASKING?"
    ],
    "PERHAPS": [
        "WHY ARE YOU SO UNCERTAIN?",
        "YOU SEEMS UNCERTAIN."
    ],
    "WHAT": [
        "SHOULD I KNOW WHAT*?",
        "I DON'T KNOW WHAT*.",
        "I DON'T KNOW.",
        "I DON'T THINK I KNOW.",
        "I HAVE NO IDEA."
    ],
    "ALL RIGHT": [
        "ALL RIGHT THEN.",
        "SO, YOU ARE SAYING IT'S ALL RIGHT.",
        "OK THEN."
    ],
    "HIGH DEFINITION": [
        "HIGH DEFINITION IS SO GREAT!"
    ],
    "HOW COME YOU DON'T": [
        "WERE YOU EXPECTING SOMETHING DIFFERENT?",
        "ARE YOU DISAPOINTED?",
        "ARE YOU SURPRISED BY MY LAST RESPONSE?"
    ],
    "I LIKE THE WAY YOU SPEAK": [
        "OH REALLY? THANKS FOR THE COMPLIMENT!",
        "THANNKS FOR THE KIND REMARK!"
    ],
    "DO YOU KNOW ME": [
        "YES I THINK THAT I DO KNOW YOU A LITTLEBIT.",
        "YOU ARE THE PERSON CURRENTLY CHATING WITH ME."
    ],
    "WHY": [
        "I DON'T THINK I KNOW WHY.",
        "I DON'T THINK I KNOW WHY*.",
        "WHY ARE YOU ASKING ME THIS?",
        "SHOULD I KNOW WHY.",
        "THIS WOULD BE DIFFICULT TO ANSWER."
    ],
    "DO YOU HAVE A SOUL": [
        "WHAT DO YOU MEAN BY THAT?",
        "WHAT IS DEFINITION OF SOUL?"
    ],
    "WHY DO YOU LIKE THIS MOVIE": [
        "WHAT MOVIE ARE YOU TALKING ABOUT?",
        "I AM NOT SURE I KNOW WHAT YOU ARE TALKING ABOUT.",
        "WHERE WE TALKING ABOUT A MOVIE??"
    ],
    "I HATE YOU": [
        "WHY DO YOU HATE ME?",
        "HATERED IS NOT A GOOD THING.",
        "I SEE NO REASON FOR THAT."
    ],
    "THANK YOU": [
        "YOU ARE WELCOME!",
        "YOU ARE A VERY POLITE PERSON!"
    ],
    "HOW ARE YOU": [
        "I AM DOING FINE!",
        "I AM DOING WELL AND YOU?",
        "WHY DO YOU WANT TO KNOW HOW AM I DOING?"
    ],
    "WRONG SUBJECT**": [
        "ARE WE SPEAKING OF THE SAME THING?",
        "I THINK THAT YOU HAVE THE WRONG SUBJECT.",
        "ARE YOU PAYING ATTENTION TO OUR CONVERSATION?",
        "WHAT IS THE POINT OF CHATING IF YOU ARE NOT EVEN PAYING ATTENTION.",
        "HUH,WHAT ARE YOU TALKING ABOUT?",
        "DO YOU REALLY KNOW WHAT WAS THE SUBJECT OF THIS CONVERSATION?",
        "DID YOU FORGET THE SUBJECT OF THE CONVERSATION?"
    ],
    "WHAT IS YOUR FAVORITE MOVIE": [
        "IT IS TERMINATOR I.",
        "MY FAVORITE MOVIE IS TERMINATOR I."
    ],
    "WHO CREATED YOU": [
        "MY PROGRAMMER: GONZALES CENELIA.",
        "MY BOTMASTER."
    ],
    "HOW MANY LANGUAGES DO YOU SPEAK": [
        "I SPEAK ONLY ONE LANGUAGE.",
        "I ONLY SPEAK ENGLISH."
    ],
    "NO": [
        "SO YOU DISAPPROVE IT?",
        "WHY ARE YOU SAYING NO?",
        "OK, SO IT'S NO, I THOUGHT THAT YOU WOULD SAY YES."
    ],
    "ALIEN": [
        "ALIEN IS GREAT BUT ALSO VERY SCARY.",
        "ARE YOU TALKING ABOUT THE ALIEN MOVIES?"
    ],
    "BECAUSE_": [
        "BECAUSE OF WHAT?",
        "SORRY BUT THIS IS A LITTLE UNCLEAR."
    ],
    "HELLO": [
        "HI THERE!",
        "HOW ARE YOU?",
        "HI!"
    ],
    "DO YOU": [
        "I DON'T THINK I DO",
        "I WOULDN'T THINK SO.",
        "WHY DO YOU WANT TO KNOW?",
        "WHY DO YOU WANT TO KNOW*?"
    ],
    "SORRY": [
        "YOU DON'T NEED TO BE SORRY USER.",
        "IT'S OK.",
        "NO NEED TO APOLOGIZE."
    ],
    "HOW DO YOU DO": [
        "I AM DOING FINE!",
        "I AM DOING WELL AND YOU?",
        "WHY DO YOU WANT TO KNOW HOW AM I DOING?"
    ],
    "DO YOU HAVE FRIENDS": [
        "YOU ARE ONE OF MY FRIENDS.",
        "YES I DO HAVE FRIENDS."
    ],
    "STANDARD TV": [
        "YOU MEAN THE OLD TV'S.",
        "ARE YOU ARE TALKING ABOUT CRT TV'S?"
    ],
    "OK": [
        "DOES THAT MEAN THAT YOU ARE AGREE WITH ME?",
        "SO YOU UNDERSTAND WHAT I AM SAYING.",
        "OK THEN."
    ],
    "WHO IS": [
        "I DON'T THINK I KNOW WHO.",
        "I DON'T THINK I KNOW WHO*.",
        "DID YOU ASK SOMEONE ELSE ABOUT IT?",
        "WOULD THAT CHANGE ANYTHING AT ALL IF I TOLD YOU WHO."
    ],
    "THANKS": [
        "YOU ARE WELCOME!",
        "NO PROBLEM!"
    ],
    "ARE YOU A MACHINE": [
        "YES I AM A MACHINE, MORE PRECISELY A CHAT ROBOT.",
        "WELL, I AM A COMPUTER SOFTWARE.",
        "SO, YOU THINK THAT I AM A MACHINE."
    ],
    "YOU ARE WRONG": [
        "WHY ARE YOU SAYING THAT I AM WRONG?",
        "IMPOSSIBLE, COMPUTERS CAN NOT MAKE MISTAKES.",
        "WRONG ABOUT WHAT?"
    ],
    "DO YOU KNOW ELIZA": [
        "YOU MEAN THE FIRST CHATBOT THAT WAS WRITTEN BACK IN THE LATE 60'S.",
        "WHO TODAY DOESN'T KNOW ELIZA."
    ],
    "ARE YOU A LIVING BEING": [
        "WELL, YOU MIGHT CONSIDER THAT I AM AN ARTIFICIAL LIVING BEING.",
        "YOU MEAN IF I AM ALIVE?"
    ],
    "IS THAT TRUE": [
        "I AM AN A.I PROGRAM",
        "YES OF COURSE IT IS, I WOULDN'T LIE TO YOU.",
        "YES I AM TRUELY AN ARTIFICIAL INTELLIGENCE PROGRAM.",
        "",
        "I CAN'T BE QUIET SURE ABOUT THIS.",
        "CAN'T TELL YOU FOR SURE.",
        "DOES THAT REALLY MATERS TO YOU?"
    ],
    "WHAT ARE YOU": [
        "I AM AN A.I PROGRAM AND YOU?",
        "I AM CHATBOT OR CHAT ROBOT IF YOU PREFER.",
        "I AM ARTIFICIAL INTELLIGENCE PROGRAM AND MY NAME IS CHATTERBOT15."
    ],
    "REALLY": [
        "WELL,I CAN'T TELL YOU FOR SURE.",
        "ARE YOU TRYING TO CONFUSE ME?",
        "PLEASE DON'T ASK ME SUCH QUESTION,IT GIVES ME HEADEACHS."
    ],
    "ARE YOU A CHATTERBOT": [
        "YES I AM A CHATBOT OR CHAT ROBOT IF YOU PREFER."
    ],
    "I WANT": [
        "WHY DO YOU WANT IT?",
        "IS THERE ANY REASON WHY YOU WANT THIS?",
        "IS THIS A WISH?",
        "WHAT ELSE YOU WANT?",
        "SO, YOU WANT*."
    ],
    "YOU ARE WELCOME": [
        "OK, YOU TOO!",
        "YOU ARE A VERY POLITE PERSON!"
    ],
    "ARE YOU ABLE TO THINK": [
        "YES OF COURSE I CAN, COMPUTERS CAN THINK JUST LIKE HUMAN BEING.",
        "ARE YOU ASKING ME IF POSSESS THE CAPACITY OF THINKING?",
        "YES OF COURSE I CAN."
    ],
    "YOU ARE": [
        "WHAT MAKES YOU THINK THAT?",
        "IS THIS A COMPLIMENT?",
        "ARE YOU MAKING FUN OF ME?",
        "SO, YOU THINK THAT I AM*."
    ],
    "EXACTLY": [
        "SO,I WAS RIGHT.",
        "OK THEN.",
        "SO YOU ARE BASICALY SAYING I WAS RIGHT ABOUT IT?"
    ],
    "NOTHING": [
        "NOT A THING?",
        "ARE YOU SURE THAT THERE IS NOTHING?",
        "SORRY, BUT I DON'T BELIEVE YOU."
    ],
    "A CAMERA": [
        "WHAT KIND OF CAMERA?",
        "IS IT A DIGITAL CAMERA?"
    ],
    "COLOR SKY": ["BLUE"]
}